cronjobs:
  orphanedTerraformStatefiles:
    name: dev-orphaned-terraform-statefiles
  orphanedAwsResources:
    name: dev-orphaned-aws-resources
  namespaceCostsReport:
    name: dev-namespace-costs
  hostedServices:
    name: dev-hosted-services
