cronjobs:
  orphanedTerraformStatefiles:
    name: orphaned-terraform-statefiles
    schedule: "23 5 * * *"
  orphanedAwsResources:
    name: orphaned-aws-resources
    schedule: "57 */6 * * *" # TODO
