cronjobs:
  orphanedTerraformStatefiles:
    name: orphaned-terraform-statefiles
    schedule: "23 5 * * *"
  orphanedAwsResources:
    name: orphaned-aws-resources
    schedule: "57 */6 * * *"
  namespaceCostsReport:
    name: namespace-costs
    schedule: "41 5 * * *"
  hostedServices:
    name: hosted-services
    schedule: "37 4 * * *"
  namespaceUsageReport:
    name: namespace-usage-report
    schedule: "11 */6 * * *"
