webApplication:
  apiSecretName: cloud-platform-reports-api-key
  apiSecretKey: token
  hostname: https://reports.cloud-platform.service.justice.gov.uk
cluster:
  fullName: live-1.cloud-platform.service.justice.gov.uk
cronjobs:
  orphanedTerraformStatefiles:
    name: orphaned-terraform-statefiles
    schedule: "23 5 * * *"
  orphanedAwsResources:
    name: orphaned-aws-resources
    schedule: "57 */6 * * *"
  namespaceCostsReport:
    name: namespace-costs
    schedule: "41 5 * * *"
  hostedServices:
    name: hosted-services
    schedule: "37 4 * * *"
  namespaceUsageReport:
    name: namespace-usage-report
    schedule: "11 */6 * * *"
  terraformModules:
    name: terraform-modules
    schedule: "7 */12 * * *"
  overdueDocumentation:
    name: overdue-documentation
    schedule: "37 */6 * * *"
  helmWhatup:
    name: helm-whatup
    schedule: "23 4 * * *"
  githubRepositories:
    name: github-repositories
    schedule: "12 5 * * *"
  liveOneDomains:
    name: live-one-domains
    schedule: "30 6 * * *"
  infraDeployments:
    name: infrastructure-deployments
    schedule: "59 23 28-31 * *"
cloudPlatformReports:
  secretName: hoodaw-api-key
