apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.ruby_deployment.name }}
spec:
  replicas: {{ .Values.ruby_deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.ruby_deployment.labels.app }}

  template:
    metadata:
      labels:
        app: {{ .Values.ruby_deployment.labels.app }}

    spec:
      serviceAccountName: cloud-platform-reports-prod-irsa
      containers:
        - name: {{ .Values.ruby_deployment.containers.webapp.name }}
          image: {{ .Values.ruby_deployment.containers.webapp.image }}:{{ .Chart.AppVersion }}
          env:
            - name: RACK_ENV
              value: "production"

            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: hoodaw-api-key    # This k8s secret is created in the environments repository
                  key: token

            - name: DYNAMODB_REGION
              value: "eu-west-2"
              
            - name: DYNAMODB_TABLE_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.dynamodb.secretName }}
                  key: table_name
          ports:
          - containerPort: {{ .Values.ruby_service.port }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.go_deployment.name }}
spec:
  replicas: {{ .Values.go_deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.go_deployment.labels.app }}

  template:
    metadata:
      labels:
        app: {{ .Values.go_deployment.labels.app }}

    spec:
      serviceAccountName: "hoodaw-production"
      containers:
        - name: {{ .Values.go_deployment.containers.webapp.name }}
          image: {{ .Values.go_deployment.containers.webapp.image }}:{{ .Chart.AppVersion }}
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: hoodaw-api-key    # This k8s secret is created in the environments repository
                  key: token
          ports:
          - containerPort: {{ .Values.go_service.port }}
