apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.labels.app }}
    spec:
      containers:
        - name: {{ .Values.deployment.containers.webapp.name }}
          image: {{ .Values.deployment.containers.webapp.image }}
          env:
            - name: RACK_ENV
              value: "production"
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.cloudPlatformReports.secretName }}
                  key: token
            - name: DYNAMODB_REGION
              value: "eu-west-2"
            - name: DYNAMODB_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.dynamodb.secretName }}
                  key: access_key_id
            - name: DYNAMODB_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.dynamodb.secretName }}
                  key: secret_access_key
            - name: DYNAMODB_TABLE_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.dynamodb.secretName }}
                  key: table_name
          ports:
          - containerPort: {{ .Values.service.port }}
