apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.labels.app }}
    spec:
      serviceAccountName: cloud-platform-reports-prod-irsa
      containers:
        - name: {{ .Values.deployment.containers.webapp.name }}
          image: {{ .Values.deployment.containers.webapp.image }}:{{ .Chart.AppVersion }}
          env:
            - name: RACK_ENV
              value: "production"
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: hoodaw-api-key    # This k8s secret is created in the environments repository
                  key: token
            - name: DYNAMODB_REGION
              value: "eu-west-2"
            - name: DYNAMODB_TABLE_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.dynamodb.secretName }}
                  key: table_name
          ports:
          - containerPort: {{ .Values.service.port }}
