apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: cloud-platform-reports-app-ingress
spec:
  tls:
  - hosts:
    - cloud-platform-reports.apps.live-1.cloud-platform.service.justice.gov.uk
  rules:
    - host: cloud-platform-reports.apps.live-1.cloud-platform.service.justice.gov.uk
      http:
        paths:
        - path: /
          backend:
            serviceName: cloud-platform-reports-service
            servicePort: 4567
