apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  annotations:
    external-dns.alpha.kubernetes.io/aws-weight: "100"
    external-dns.alpha.kubernetes.io/set-identifier: "hoodaw-live"
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.hostname }}
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
        - path: /
          backend:
            serviceName: {{ .Values.service.name }}
            servicePort: {{ .Values.service.port }}
