apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: cloud-platform-reports-app-ingress
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.hostname }}
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
        - path: /
          backend:
            serviceName: cloud-platform-reports-service
            servicePort: 4567
