apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cloudPlatformReports.secretName }}
type: Opaque
stringData:
  token: {{ .Values.cloudPlatformReports.apiKey }}
---
# This secret will be created automatically by the cloud platform DynamoDB terraform module,
# so we won't actually need this section or the corresponding parts of secrets.yaml, after
# we migrate the application to the new namespace
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.dynamodb.secretName }}
type: Opaque
stringData:
  access_key_id: {{ .Values.dynamodb.access_key_id }}
  secret_access_key: {{ .Values.dynamodb.secret_access_key }}
  table_name: {{ .Values.dynamodb.table_name }}
