apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ruby_service.name }}
  labels:
    app: {{ .Values.ruby_service.name }}
spec:
  ports:
  - port: {{ .Values.ruby_service.port }}
    name: https
    targetPort: {{ .Values.ruby_service.port }}
  selector:
    app: {{ .Values.ruby_deployment.labels.app }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.go_service.name }}
  labels:
    app: {{ .Values.go_service.name }}
spec:
  ports:
  - port: {{ .Values.go_service.port }}
    name: https
    targetPort: {{ .Values.go_service.port }}
  selector:
    app: {{ .Values.go_deployment.labels.app }}
