apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.webApplication.apiSecretName }}
type: Opaque
stringData:
  {{ .Values.webApplication.apiSecretKey }}: {{ .Values.cloudPlatformReports.apiKey }}
  hostname: {{ .Values.webApplication.hostname }} # For the dashboard reporter concourse job
