# This secret allows the cronjobs to pull images from docker hub without
# running into the download limits that apply to anonymous pulls.
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ .Values.dockerhubCredentials.secretName }}
data:
  .dockerconfigjson: {{ .Values.dockerhubCredentials.dockerconfigjson }}
