apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Values.cronjobs.namespaceUsageReport.name }}
spec:
  schedule: "{{ .Values.cronjobs.namespaceUsageReport.schedule }}"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 100
      template:
        spec:
          containers:
          - name: namespace-usage-reporter
            image: "registry.hub.docker.com/ministryofjustice/cloud-platform-namespace-usage-reporter:non-root" # TODO: switch to the 'official' release tag
            securityContext:
              runAsUser: 1000
            env:
            - name: AWS_REGION
              value: eu-west-2
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-creds
                  key: access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-creds
                  key: secret-access-key
            {{- template "cloud-platform-reports-cronjobs.hoodaw-credentials" . }}
            - name: KUBECONFIG
              value: /tmp/kubeconfig
            - name: KUBECONFIG_S3_BUCKET
              value: cloud-platform-concourse-kubeconfig
            - name: KUBECONFIG_S3_KEY
              value: kubeconfig
            - name: KUBE_CLUSTER
              value: live-1.cloud-platform.service.justice.gov.uk
            args:
              - /app/bin/post_namespace_usage_data.sh
          restartPolicy: OnFailure
