apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.cronjobs.namespaceCostsReport.name }}
spec:
  schedule: "{{ .Values.cronjobs.namespaceCostsReport.schedule }}"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 100
      template:
        spec:
          {{- include "cloud-platform-reports-cronjobs.imagePullSecrets" . | indent 10 }}
          containers:
          - name: namespace-cost-calculator
            image: ministryofjustice/cloud-platform-cost-calculator:4.3.1
            securityContext:
              runAsUser: 1000
              allowPrivilegeEscalation: false
              runAsNonRoot: true
              seccompProfile:
                type: RuntimeDefault
              capabilities:
                drop: [ "ALL" ]
            env:
            - name: HOODAW_BUCKET
              value: cloud-platform-hoodaw-reports
            - name: AWS_REGION
              value: eu-west-2
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-creds
                  key: access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-creds
                  key: secret-access-key
            {{- include "cloud-platform-reports-cronjobs.kubeconfigLocation" . | indent 12 }}
            {{- include "cloud-platform-reports-cronjobs.hoodaw-credentials" . | indent 12 }}
            command:
            - /bin/sh
            - -c
            - ./namespace-costs
          restartPolicy: OnFailure
