apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Values.cronjobs.namespaceCostsReport.name }}
spec:
  schedule: "{{ .Values.cronjobs.namespaceCostsReport.schedule }}"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 100
      template:
        spec:
          {{- template "cloud-platform-reports-cronjobs.imagePullSecrets" . }}
          containers:
          - name: namespace-cost-calculator
            image: "registry.hub.docker.com/ministryofjustice/cloud-platform-cost-calculator:2.1"
            securityContext:
              runAsUser: 1000
            env:
            {{- template "cloud-platform-reports-cronjobs.awsCredentials" . }}
            {{- template "cloud-platform-reports-cronjobs.hoodaw-credentials" . }}
            args:
              - /root/post-namespace-costs.rb
          restartPolicy: OnFailure
