apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Values.cronjobs.namespaceUsageReport.name }}
spec:
  schedule: "{{ .Values.cronjobs.namespaceUsageReport.schedule }}"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 100
      template:
        spec:
          {{- include "cloud-platform-reports-cronjobs.imagePullSecrets" . | indent 10 }}
          containers:
          - name: namespace-usage-reporter
            image: ministryofjustice/cloud-platform-namespace-usage-reporter:{{ .Chart.AppVersion }}
            securityContext:
              runAsUser: 1000
            env:
            {{- include "cloud-platform-reports-cronjobs.awsCredentials" . | indent 12 }}
            {{- include "cloud-platform-reports-cronjobs.hoodaw-credentials" . | indent 12 }}
            {{- include "cloud-platform-reports-cronjobs.kubeconfigLocation" . | indent 12 }}
            command:
            - /bin/sh
            - -c
            - ./namespace-usage
          restartPolicy: OnFailure
