apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Values.cronjobs.namespaceCostsReport.name }}
spec:
  schedule: "{{ .Values.cronjobs.namespaceCostsReport.schedule }}"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 100
      template:
        spec:
          containers:
          - name: namespace-cost-calculator
            image: "registry.hub.docker.com/ministryofjustice/cloud-platform-cost-calculator:2.1"
            securityContext:
              runAsUser: 1000
            env:
            - name: AWS_REGION
              value: eu-west-2
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-creds
                  key: access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-creds
                  key: secret-access-key
            - name: HOODAW_API_KEY
              valueFrom:
                secretKeyRef:
                  name: hoodaw-creds
                  key: api_key
            - name: HOODAW_HOST
              value: "https://{{ .Values.ingress.hostname }}"
            args:
              - /root/post-namespace-costs.rb
          restartPolicy: OnFailure
