apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Values.cronjobs.namespaceUsageReport.name }}
spec:
  schedule: "{{ .Values.cronjobs.namespaceUsageReport.schedule }}"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 100
      template:
        spec:
          {{- template "cloud-platform-reports-cronjobs.imagePullSecrets" . }}
          containers:
          - name: namespace-usage-reporter
            image: "registry.hub.docker.com/ministryofjustice/cloud-platform-namespace-usage-reporter:non-root" # TODO: switch to the 'official' release tag
            securityContext:
              runAsUser: 1000
            env:
            {{- template "cloud-platform-reports-cronjobs.awsCredentials" . }}
            {{- template "cloud-platform-reports-cronjobs.hoodaw-credentials" . }}
            {{- template "cloud-platform-reports-cronjobs.kubeconfigLocation" . }}
            - name: KUBE_CLUSTER
              value: live-1.cloud-platform.service.justice.gov.uk
            args:
              - /app/bin/post_namespace_usage_data.sh
          restartPolicy: OnFailure
