apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Values.cronjobs.orphanedAwsResources.name }}
spec:
  schedule: "{{ .Values.cronjobs.orphanedAwsResources.schedule }}"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 100
      template:
        spec:
          {{- include "cloud-platform-reports-cronjobs.imagePullSecrets" . | indent 10 }}
          containers:
          - name: orphaned-terraform-statefiles
            image: ministryofjustice/cloud-platform-report-orphaned-resources:{{ .Chart.AppVersion }}
            securityContext:
              runAsUser: 1000
            env:
            {{- include "cloud-platform-reports-cronjobs.awsCredentials" . | indent 12 }}
            {{- include "cloud-platform-reports-cronjobs.hoodaw-credentials" . | indent 12 }}
            args:
              - /bin/sh
              - -c
              - |-
                cd /app
                ./bin/post-data-to-hoodaw.sh
          restartPolicy: OnFailure
